# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d98b9b14c94fbf9ff40247cd638cfeb31656321ccdb192b04a6b7204872806086394f43cec9e97390e9f97d169f39272edeba2e81008c7c6936a9fa20a57609

test:
  secret_key_base: 9e8e51ce7d742626b19e2d400ce1af4b8e4d0c5dd977c1a86f88eed20fe5aac609ecd490f6f580a93c0f56868bd2da0196530f216d05e1c8257916bfcd0b6eb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
